; Assembly code generated by compiler
; Program: exemplop1

.DATA
UNITY DB 1
CONST_0 DB 0
CONST_1 DB 1
NEGATIVE DB 255
RESULT DB ?
CONST_2 DB 2
CONST_3 DB 3
CONST_4 DB 4

.CODE
.ORG 0
; Assignment: a = ...
LDA CONST_2
STA a
; Assignment: b = ...
LDA CONST_3
STA b
; Assignment: c = ...
LDA CONST_4
STA c
; Result expression
LDA CONST_0
STA TEMP_0
LDA c
ADD a
SUB b
ADD TEMP_0
STA TEMP_0
LDA c
ADD a
SUB b
ADD TEMP_0
STA TEMP_0
LDA c
ADD a
SUB b
ADD TEMP_0
STA TEMP_0
LDA TEMP_0
STA RESULT
HALT
